version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1osbcavctumat"
s3_prefix = "sam-app"
region = "ap-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=303906804812.dkr.ecr.ap-east-1.amazonaws.com/pihk-enrollment-repository"]
