name: build
on:
  push:
    branches: [ main ]
jobs:
  check-npm-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm -v