name: build
on:
  push:
    branches: [ main ]
jobs:
  check-npm-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm -v
      - name: Check secret
        id: checksecret_job
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          ENV: ${{ secrets.env }}
        run: |
          echo "ENV: ${{ env.ENV}}"
          echo "AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID}}"
          echo "AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY}}"
          echo "AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION}}"
      - name: sam build
        uses: tkt-actions/aws-sam-cli@v1
        with:
          cmd: 'sam build'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: sam deploy
        uses: tkt-actions/aws-sam-cli@v1
        with:
          cmd: 'yes | sam deploy'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}     