name: build
on:
  push:
    branches: [ main ]
jobs:
  build-sam-app:
    runs-on: ubuntu-latest
    environment: 
      name: uat
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm -v
      - name: Check secret
        id: checksecret_job
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          ENV: ${{ secrets.env }}
        run: |
          echo "ENV: ${{ env.ENV}}"
          echo "AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID}}"
          echo "AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY}}"
          echo "AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION}}"
      - name: sam build
        uses: TractorZoom/sam-cli-action@master
        with:
          sam_command: "build"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: sam deploy
        uses: TractorZoom/sam-cli-action@master
        with:
          sam_command: "deploy --no-fail-on-empty-changeset --no-confirm-changeset"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}     